In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Yes, there is a difference in the data type of the variables list_ and array_list even though they contain the same elements. Here's the code to print their data types:

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [7]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of array_list: ", array_list.dtype)

# Access and check data type of individual elements (using a loop)
for element in array_list:
  print("Data type of element:", type(element))


Data type of array_list:  <U1
Data type of element: <class 'numpy.str_'>
Data type of element: <class 'numpy.str_'>
Data type of element: <class 'numpy.str_'>
Data type of element: <class 'numpy.str_'>
Data type of element: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

Ans. Yes, there will be a difference in the data type of the elements in list_ and array_list if you use np.array(object=list_, dtype=int)

In [8]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

# Create array with data type set to integer
array_list = np.array(object=list_, dtype=int)

# Print data type of the entire array
print("Data type of array_list: ", array_list.dtype)

# Print data type of individual elements (using a loop)
for element in array_list:
  print("Data type of element:", type(element))


Data type of array_list:  int64
Data type of element: <class 'numpy.int64'>
Data type of element: <class 'numpy.int64'>
Data type of element: <class 'numpy.int64'>
Data type of element: <class 'numpy.int64'>
Data type of element: <class 'numpy.int64'>


import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [11]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_array)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [12]:
import numpy as np

zero_matrix = np.zeros((3, 3))
print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [13]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
